spring:
  application:
    name: helloserver

server:
  port: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaulZone: http://localhost:8761/eureka/
      instance: 
      hostname: localhost
#docker run -d -p 9099:8061 bootdocker:latest
